# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qm3ruduMNJmYcUDyXB9ZQD3GKWULvPWo
"""

import streamlit as st
import yfinance as yf
import pandas as pd

# Konfigurasi Halaman Streamlit
st.set_page_config(
    page_title="Dashboard Real-Time Seluruh Saham Indonesia (IDX)",
    layout="wide"
)

st.title("🇮🇩 Dashboard Real-Time Saham Bursa Efek Indonesia (IDX)")
st.markdown(
    "Memantau pergerakan harga saham emiten di Indonesia secara langsung, terintegrasi dengan data "
    "**Yahoo Finance**, **IDX**, **TradingView**, dan **Investing.com**."
)

# Daftar emiten utama/unggulan BEI (IDX) yang dapat diperluas
@st.cache_data(ttl=3600)
def get_idx_universe():
    return [
        "BBCA.JK", "BBRI.JK", "BMRI.JK", "BBNI.JK", "TLKM.JK",
        "ASII.JK", "UNVR.JK", "ICBP.JK", "INDF.JK", "GOTO.JK",
        "ADRO.JK", "PTBA.JK", "ANTM.JK", "MDKA.JK", "UNTR.JK",
        "KLBF.JK", "SMGR.JK", "CPIN.JK", "INKP.JK", "MEDC.JK",
        "ARTO.JK", "BRIS.JK", "PGAS.JK", "BUKA.JK", "JSMR.JK",
        "BUMI.JK", "ENRG.JK", "HRUM.JK", "ADMR.JK", "INCO.JK"
    ]

all_tickers = get_idx_universe()

# Sidebar Navigasi dan Pencarian Saham
st.sidebar.header("🔍 Pencarian Saham IDX")
selected_ticker = st.sidebar.selectbox("Pilih Emiten Populer:", all_tickers)
custom_ticker = st.sidebar.text_input("Atau Ketik Kode Saham Lain (contoh: BBCA):", value="")

# Menyesuaikan input manual dengan format Yahoo Finance (.JK)
target_ticker = custom_ticker.strip().upper() if custom_ticker.strip() else selected_ticker
if not target_ticker.endswith(".JK") and target_ticker:
    target_ticker += ".JK"

if st.sidebar.button("🔄 Perbarui Data"):
    st.rerun()

# Fungsi Mengambil Data Historis & Info Detail
@st.cache_data(ttl=60)
def fetch_stock_data(ticker):
    stock = yf.Ticker(ticker)
    df = stock.history(period="1mo", interval="1d")
    info = stock.info
    return df, info

try:
    with st.spinner(f"Mengambil data real-time untuk {target_ticker}..."):
        df, info = fetch_stock_data(target_ticker)

    if not df.empty:
        current_price = df['Close'].iloc[-1]
        prev_close = info.get('previousClose', df['Close'].iloc[-2] if len(df) > 1 else current_price)
        change = current_price - prev_close
        pct_change = (change / prev_close) * 100 if prev_close else 0

        # Metrik Utama Saham Pilihan
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Harga Terakhir", f"Rp {current_price:,.2f}", f"{pct_change:.2f}%")
        col2.metric("Tertinggi (1 Bulan)", f"Rp {df['High'].max():,.2f}")
        col3.metric("Terendah (1 Bulan)", f"Rp {df['Low'].min():,.2f}")
        col4.metric("Volume Hari Ini", f"{int(df['Volume'].iloc[-1]):,}")

        # Grafik Pergerakan Harga
        st.subheader(f"📈 Grafik Pergerakan Harga Saham: {target_ticker}")
        st.line_chart(df['Close'])

        # Tabel Ringkasan Kolektif Saham IDX
        st.subheader("📋 Ringkasan Pasar Saham Utama IDX")

        @st.cache_data(ttl=300)
        def fetch_market_summary(tickers_list):
            data_list = []
            for t in tickers_list:
                try:
                    t_obj = yf.Ticker(t)
                    hist = t_obj.history(period="2d")
                    if not hist.empty:
                        last_p = hist['Close'].iloc[-1]
                        prev_p = hist['Close'].iloc[-2] if len(hist) > 1 else last_p
                        chg = ((last_p - prev_p) / prev_p) * 100
                        data_list.append({
                            "Kode Saham": t,
                            "Harga Terakhir (IDR)": round(last_p, 2),
                            "Perubahan (%)": round(chg, 2),
                            "Volume": int(hist['Volume'].iloc[-1])
                        })
                except Exception:
                    continue
            return pd.DataFrame(data_list)

        summary_df = fetch_market_summary(all_tickers)
        if not summary_df.empty:
            st.dataframe(summary_df, use_container_width=True)

    else:
        st.warning("Data saham tidak ditemukan. Pastikan kode emiten sudah benar.")

except Exception as e:
    st.error(f"Gagal memuat data pasar: {e}")

# Integrasi Tautan Langsung ke Situs Sumber Data
st.markdown("---")
st.subheader("🔗 Akses Cepat Platform Sumber Terkait")
clean_sym = target_ticker.replace(".JK", "")

col_a, col_b, col_c, col_d = st.columns(4)

with col_a:
    st.markdown("**TradingView**")
    st.markdown(f"[Buka Grafik TA](https://www.tradingview.com/chart/?symbol=IDX:{clean_sym})")

with col_b:
    st.markdown("**Yahoo Finance**")
    st.markdown(f"[Cek Market Info](https://finance.yahoo.com/quote/{target_ticker})")

with col_c:
    st.markdown("**Investing.com**")
    st.markdown(f"[Analisis & Berita](https://www.investing.com/equities/{clean_sym.lower()}-indonesia)")

with col_d:
    st.markdown("**IDX (Bursa Efek)**")
    st.markdown("[Situs Resmi BEI](https://www.idx.co.id/)")